package tw.com.tm.erp.utils;

import java.util.List;

import tw.com.tm.erp.hbm.bean.SoSalesOrderItem;


//Generated by MyEclipse

public interface ISoSalesOrderItemService {
	
	public List<SoSalesOrderItem> getT2PosItems(String patTrdno, java.util.Date patHdate);
	
}